// frontend/src/contexts/LanguageContext.jsx
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // ========== COMMON ==========

    schemes_data_en: [
  {
    id: 1,
    scheme_name: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
    description: "Income support scheme providing ₹6000 per year to small and marginal farmers.",
    eligibility: "All small and marginal farmers owning cultivable land.",
    benefits: "₹6000 per year in three equal installments directly into bank account.",
    application_link: "https://pmkisan.gov.in/"
  },
  {
    id: 2,
    scheme_name: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    description: "Crop insurance scheme to protect farmers against crop loss due to natural disasters.",
    eligibility: "Farmers growing notified crops in notified areas.",
    benefits: "Insurance coverage and financial support in case of crop failure.",
    application_link: "https://pmfby.gov.in/"
  },
  {
    id: 3,
    scheme_name: "Mahatma Jyotirao Phule Shetkari Karj Mukti Yojana",
    description: "Loan waiver scheme launched by Maharashtra government for farmers.",
    eligibility: "Farmers with crop loans from banks in Maharashtra.",
    benefits: "Loan waiver up to ₹2 lakh.",
    application_link: "https://mjpsky.maharashtra.gov.in/"
  },
  {
    id: 4,
    scheme_name: "Soil Health Card Scheme",
    description: "Provides soil health cards to farmers with recommendations for fertilizers.",
    eligibility: "All farmers across India.",
    benefits: "Better crop productivity and reduced fertilizer cost.",
    application_link: "https://soilhealth.dac.gov.in/"
  },
  {
    id: 5,
    scheme_name: "Kisan Credit Card (KCC)",
    description: "Provides farmers with easy credit for agriculture and allied activities.",
    eligibility: "Farmers engaged in agriculture or allied activities.",
    benefits: "Short-term credit with low interest rates.",
    application_link: "https://www.myscheme.gov.in/schemes/kcc"
  }
],
    
    app_name: "AgriSmart AI",
    home: "Home",
    features: "Features",
    about: "About",
    contact: "Contact",
    sign_in: "Sign In",
    sign_up: "Sign Up",
    dashboard: "Dashboard",
    marketplace: "Marketplace",
    schemes: "Schemes",
    my_orders: "My Orders",
    logout: "Log Out",
    loading: "Loading...",
    error: "Error",
    retry: "Retry",
    back_home: "← Back Home",
    days: "days",
    
    // ========== HOME PAGE ==========
    hero_title: "Smart Agriculture",
    hero_title_gradient: "AI-Powered Solutions",
    hero_subtitle: "Revolutionizing farming with cutting-edge artificial intelligence. Analyze, optimize, and maximize your agricultural yield.",
    explore_features: "Explore Features",
    get_started_free: "Get Started Free",
    our_tools: "Our AI-Powered Tools",
    soybean_analyzer: "Soybean Analyzer",
    soybean_desc: "AI-powered seed damage detection with pest analysis",
    fertilizer_optimizer: "Fertilizer Optimizer",
    fertilizer_desc: "Smart fertilizer recommendations",
    budget_optimizer: "Budget Optimizer",
    budget_desc: "Maximize yield with optimal allocation",
    weather_insights: "Weather Insights",
    weather_desc: "Real-time weather & farming recommendations",
    learn_more: "Learn More →",
    stat_detection_accuracy: "Detection Accuracy",
    stat_yield_increase: "Yield Increase",
    stat_happy_farmers: "Happy Farmers",
    stat_ai_assistance: "AI Assistance",
    footer_copyright: "© 2024 AgriSmart AI. All rights reserved.",
    
    // ========== NAVBAR ==========
    soybean: "Soybean",
    fertilizer: "Fertilizer",
    budget: "Budget",
    weather: "Weather",
    our_mission: "Our Mission",
    our_team: "Our Team",
    
    // ========== SOYBEAN ANALYZER ==========
    
    soybean_title: "Soybean Seed Analyzer",
    soybean_subtitle: "AI-powered seed damage detection and pest infestation analysis",
    select_images: "Drop your seed images here",
    upload_hint_single: "Upload 1 image for analysis",
    upload_hint_batch: "Upload up to 10 images for batch analysis",
    upload_analyze: "Start {mode}",
    analyzing_seeds: "Analyzing Seeds...",
    total_seeds: "Total Seeds",
    damaged: "Damaged",
    quality: "Quality",
    healthy: "Healthy",
    moderate_damage: "Moderate Damage",
    severe_damage: "Severe Damage",
    class_distribution: "Class Distribution",
    recommendations: "Recommendations",
    individual_analysis: "Individual Seed Analysis",
    seed_id_label: "Seed #",
    confidence_label: "Confidence",
    severity_level: "Severity Level",
    top_predictions: "Top 3 Predictions",
    filename: "Filename",
    ai_attention_map: "AI Attention Map",
    heatmap_caption: "Heatmap shows which areas influenced the model's decision",
    show: "Show",
    hide: "Hide",
    single_analysis: "Single Analysis",
    batch_analysis: "Batch Analysis",
    grad_cam_analysis: "Grad-CAM Analysis",
    single_desc: "Analyze one seed with detailed results including top predictions",
    batch_desc: "Analyze multiple seeds with class distribution",
    grad_desc: "Visual explanation of AI decisions with heatmap",
    max_image: "Max: {count} image",
    max_images: "Max: {count} images",
    
    // ========== FERTILIZER OPTIMIZER ==========
    fertilizer_title: "Smart Crop & Fertilizer Advisor",
    fertilizer_subtitle: "ML-Powered Crop Recommendations • Real-time Analysis • Maximum Profit",
    accuracy_badge: "98% Accuracy",
    crops_badge: "20+ Crops",
    live_analysis: "Live Analysis",
    field_params: "Field Parameters",
    enter_conditions: "Enter your soil and weather conditions",
    detect_location: "Detect My Location",
    type_location: "Type Location",
    fetching: "Fetching...",
    searching: "Searching...",
    get_weather_data: "Get Weather Data",
    cancel: "Cancel",
    city: "City *",
    country_optional: "Country (optional)",
    city_placeholder: "e.g., London",
    country_placeholder: "e.g., UK",
    soil_type: "Soil Type",
    temperature: "Temperature (°C)",
    humidity: "Humidity (%)",
    soil_moisture: "Soil Moisture (%)",
    nitrogen: "Nitrogen (N) - mg/kg",
    phosphorous: "Phosphorous (P) - mg/kg",
    potassium: "Potassium (K) - mg/kg",
    soil_ph: "Soil pH",
    previous_crop: "Previous Crop",
    season: "Season",
    auto: "Auto",
    est: "Est.",
    required: "Required",
    openweathermap: "OpenWeatherMap",
    weather_data_from: "Weather data from {location}",
    manual_input_reminder: "Please enter Nitrogen (N), Phosphorous (P), and Potassium (K) values manually",
    get_recommendations: "Get Recommendations",
    analyzing: "Analyzing...",
    top_match: "Top Match",
    soil_health: "Soil Health",
    npk: "N-P-K",
    top_crops: "Top Crop Recommendations",
    click_to_optimize: "Click on any crop to optimize fertilizer budget",
    best_match: "Best Match",
    ml_score: "ML Score:",
    soil_label: "Soil:",
    ph_label: "pH:",
    previous_crop_info: "Previous crop: {crop} | Season: {season}",
    click_optimize_budget: "💰 Click to optimize fertilizer budget →",
    farming_advice: "Farming Advice",
    
    // ========== BUDGET OPTIMIZER ==========
    budget_title: "Budget Optimizer",
    budget_info: "Optimize fertilizer purchase for {crop} based on your budget and land area",
    budget_label: "💰 Budget (₹)",
    area_label: "🌾 Land Area (hectares)",
    optimize_budget: "Optimize Budget",
    total_budget: "Total Budget",
    area_ha: "Area",
    expected_profit: "Expected Profit",
    roi: "ROI",
    revenue: "Revenue",
    spent: "Spent",
    yield_tons: "Yield",
    recommended_fertilizer: "Recommended Fertilizer Combination",
    new_calculation: "New Calculation",
    back: "Back",
    
    // ========== WEATHER PAGE ==========
    weather_forecast: "Weather Forecast",
    weather_subtitle: "7-day detailed weather analysis for your farm",
    search_city: "Search city or zip code...",
    daily_view: "Daily View",
    detailed_analysis: "Detailed Analysis",
    feels_like: "Feels like",
    humidity_short: "Humidity",
    wind_speed: "Wind Speed",
    rainfall: "Rainfall",
    pressure: "Pressure",
    smart_farming_recommendations: "Smart Farming Recommendations",
    seven_day_forecast: "7-Day Weather Forecast",
    live_location: "Live Location",
    ip_based: "IP Based",
    searched: "Searched",
    updated_at: "Updated",
    sunrise: "Sunrise",
    sunset: "Sunset",
    uv_index: "UV Index",
    moon_phase: "Moon Phase",
    rain_chance: "Rain Chance",
    snow_chance: "Snow Chance",
    farming_advice_for_day: "Farming Advice for this Day:",
    weekly_weather_analysis: "Weekly Weather Analysis",
    temperature_trends: "Temperature Trends",
    average_high: "Average High",
    average_low: "Average Low",
    temperature_range: "Temperature Range",
    rainfall_summary: "Rainfall Summary",
    total_rainfall: "Total Rainfall",
    rainy_days: "Rainy Days",
    max_rainfall: "Max Rainfall",
    wind_humidity: "Wind & Humidity",
    avg_wind_speed: "Avg Wind Speed",
    avg_humidity: "Avg Humidity",
    uv_index_range: "UV Index Range",
    recommended_activities: "Recommended Activities This Week",
    avoid_spraying: "🚫 Avoid spraying",
    irrigation_needed: "💧 Irrigation needed",
    frost_protection: "❄️ Frost protection",
    good_for_planting: "✅ Good for planting",
    high_temp_advice: "High temperature - ensure adequate irrigation",
    low_temp_advice: "Low temperature - protect sensitive crops",
    heavy_rain_advice: "Heavy rainfall expected - ensure proper drainage",
    no_rain_advice: "No rain - plan irrigation accordingly",
    strong_wind_advice: "Strong winds - secure structures and avoid spraying",
    high_humidity_advice: "High humidity - watch for fungal diseases",
    fetching_weather: "Fetching weather data for your location...",
    weather_unavailable: "Oops! Weather Data Unavailable",
    retry: "Retry",
    
    // ========== MARKETPLACE ==========
    marketplace_title: "Marketplace",
    buy_products: "Buy Products",
    sell_products: "Sell Products",
    fertilizer_tools: "Fertilizer & Tools",
    store_page: "Store Page (to be built)",
    
    // ========== BUY PRODUCTS ==========
    search_products: "Search products...",
    all_categories: "all",
    vegetables: "vegetables",
    grains: "grains",
    fruits: "fruits",
    fertilizers: "fertilizers",
    seeds: "seeds",
    tools: "tools",
    pesticides: "pesticides",
    no_products: "No products found.",
    buy_now: "Buy Now",
    your_product: "Your product",
    seller: "Seller",
    price: "Price",
    quantity: "Quantity",
    description: "Description",
    location: "Location",
    loading_products: "Loading products...",
    purchase_request_sent: "Purchase request sent!",
    enter_quantity: "Enter quantity:",
    
    // ========== SELL PRODUCTS ==========
    sell_title: "Sell Your Product",
    edit_product: "Edit Product",
    product_name: "Product Name *",
    category: "Category *",
    price_placeholder: "Price (₹) *",
    quantity_placeholder: "Quantity *",
    location_placeholder: "City, District",
    description_placeholder: "Description",
    product_image: "Product Image",
    list_product: "List Product",
    update_product: "Update Product",
    your_listings: "Your Listed Products",
    edit: "Edit",
    delete: "Delete",
    current_image: "Current image",
    uploading: "Uploading...",
    product_updated: "Product updated!",
    product_listed: "Product listed!",
    are_you_sure: "Are you sure?",
    delete_failed: "Delete failed",
    
    // ========== DASHBOARD ==========
    farmer_dashboard: "Farmer Dashboard",
    total_products_listed: "Total Products Listed",
    orders_received: "Orders Received",
    government_schemes: "Government Schemes",
    manage_products: "Manage Products →",
    view_orders: "View Orders →",
    view_all_schemes: "View All Schemes →",
    loading_dashboard: "Loading dashboard...",
    
    // ========== GOVERNMENT SCHEMES ==========
    gov_schemes_title: "Government Schemes for Maharashtra Farmers",
    eligibility_label: "Eligibility:",
    benefits_label: "Benefits:",
    apply_now: "Apply Now →",
    loading_schemes: "Loading schemes...",
    
    // ========== MY ORDERS ==========
    my_orders_title: "My Orders",
    buying: "Buying",
    selling: "Selling",
    placed: "Placed",
    accept: "Accept",
    reject: "Reject",
    pending: "pending",
    accepted: "accepted",
    rejected: "rejected",
    loading_orders: "Loading orders...",
    no_orders: "No orders found.",
    accept_btn: "Accept",
    reject_btn: "Reject",
    status_update_failed: "Status update failed",
    
    // ========== ORDER HISTORY (modal) ==========
    order_history: "Order History",
    no_orders_yet: "No orders yet.",
    order_total: "Total",
    each: "each",
    
    // ========== CHATBOT ==========
    ai_assistant: "AgriSmart AI Assistant",
    powered_by: "Powered by Google Gemini 2.5 Flash",
    ask_me: "Ask me anything about agriculture...",
    welcome_message: "Hello! 👋 I'm your agricultural AI assistant. Ask me about crop management, pest control, irrigation, market prices, government schemes, and more!",
    try_asking: "Try asking me:",
    crop_management: "🌾 Crop management",
    pest_control: "🐛 Pest control",
    irrigation: "💧 Irrigation techniques",
    market_prices: "📈 Market prices",
    gov_schemes_chat: "🏛️ Government schemes",
    type_message: "Type your message...",
    clear_chat: "Clear chat",
    send: "Send",
    error_message_chat: "Sorry, I encountered an error. Please try again later.",
    network_error: "Network error. Please check your internet connection.",
    too_many_requests: "Too many requests. Please wait a moment and try again.",
    server_error: "Server error. Please try again in a few moments.",
    rate_limit_warning: "⚠️ You've hit the rate limit. Please wait a moment before sending more messages.",
  },
  
  hi: {
    // Hindi translations – fallback to English for keys not yet translated

    schemes_data_hi: [
  {
    id: 1,
    scheme_name: "प्रधानमंत्री किसान सम्मान निधि (पीएम-किसान)",
    description: "छोटे और सीमांत किसानों को ₹6000 प्रति वर्ष प्रदान करने वाली आय सहायता योजना।",
    eligibility: "कृषि योग्य भूमि रखने वाले सभी छोटे और सीमांत किसान।",
    benefits: "₹6000 प्रति वर्ष तीन समान किस्तों में सीधे बैंक खाते में।",
    application_link: "https://pmkisan.gov.in/"
  },
  {
    id: 2,
    scheme_name: "प्रधानमंत्री फसल बीमा योजना (पीएमएफबीवाई)",
    description: "प्राकृतिक आपदाओं के कारण फसल नुकसान से किसानों की रक्षा के लिए फसल बीमा योजना।",
    eligibility: "अधिसूचित क्षेत्रों में अधिसूचित फसलें उगाने वाले किसान।",
    benefits: "फसल विफलता की स्थिति में बीमा कवरेज और वित्तीय सहायता।",
    application_link: "https://pmfby.gov.in/"
  },
  {
    id: 3,
    scheme_name: "महात्मा ज्योतिराव फुले शेतकरी कर्ज मुक्ती योजना",
    description: "महाराष्ट्र सरकार द्वारा किसानों के लिए शुरू की गई ऋण माफी योजना।",
    eligibility: "महाराष्ट्र में बैंकों से फसल ऋण लेने वाले किसान।",
    benefits: "₹2 लाख तक का ऋण माफी।",
    application_link: "https://mjpsky.maharashtra.gov.in/"
  },
  {
    id: 4,
    scheme_name: "मृदा स्वास्थ्य कार्ड योजना",
    description: "किसानों को उर्वरकों के लिए सिफारिशों के साथ मृदा स्वास्थ्य कार्ड प्रदान करता है।",
    eligibility: "भारत के सभी किसान।",
    benefits: "बेहतर फसल उत्पादकता और कम उर्वरक लागत।",
    application_link: "https://soilhealth.dac.gov.in/"
  },
  {
    id: 5,
    scheme_name: "किसान क्रेडिट कार्ड (केसीसी)",
    description: "किसानों को कृषि और संबद्ध गतिविधियों के लिए आसान ऋण प्रदान करता है।",
    eligibility: "कृषि या संबद्ध गतिविधियों में लगे किसान।",
    benefits: "कम ब्याज दरों के साथ अल्पकालिक ऋण।",
    application_link: "https://www.myscheme.gov.in/schemes/kcc"
  }
],

    app_name: "एग्रीस्मार्ट एआई",
    home: "होम",
    features: "फीचर्स",
    about: "हमारे बारे में",
    contact: "संपर्क करें",
    sign_in: "साइन इन करें",
    sign_up: "साइन अप करें",
    dashboard: "डैशबोर्ड",
    marketplace: "मार्केटप्लेस",
    schemes: "सरकारी योजनाएं",
    my_orders: "मेरे ऑर्डर",
    logout: "लॉग आउट",
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    retry: "पुनः प्रयास करें",
    back_home: "← होम पर वापस जाएं",
    days: "दिन",
    
    hero_title: "स्मार्ट कृषि",
    hero_title_gradient: "एआई-संचालित समाधान",
    hero_subtitle: "अत्याधुनिक कृत्रिम बुद्धिमत्ता के साथ खेती में क्रांति लाना। अपनी कृषि उपज का विश्लेषण करें, अनुकूलन करें और अधिकतम करें।",
    explore_features: "सुविधाएं देखें",
    get_started_free: "मुफ्त शुरू करें",
    our_tools: "हमारे एआई-संचालित उपकरण",
    soybean_analyzer: "सोयाबीन विश्लेषक",
    soybean_desc: "एआई-संचालित बीज क्षति का पता लगाना और कीट विश्लेषण",
    fertilizer_optimizer: "उर्वरक ऑप्टिमाइज़र",
    fertilizer_desc: "स्मार्ट उर्वरक सिफारिशें",
    budget_optimizer: "बजट ऑप्टिमाइज़र",
    budget_desc: "इष्टतम आवंटन के साथ उपज को अधिकतम करें",
    weather_insights: "मौसम अंतर्दृष्टि",
    weather_desc: "वास्तविक समय मौसम और कृषि सिफारिशें",
    learn_more: "और जानें →",
    stat_detection_accuracy: "पता लगाने की सटीकता",
    stat_yield_increase: "उपज वृद्धि",
    stat_happy_farmers: "संतुष्ट किसान",
    stat_ai_assistance: "एआई सहायता",
    footer_copyright: "© 2024 एग्रीस्मार्ट एआई। सर्वाधिकार सुरक्षित।",
    
    soybean: "सोयाबीन",
    fertilizer: "उर्वरक",
    budget: "बजट",
    weather: "मौसम",
    our_mission: "हमारा मिशन",
    our_team: "हमारी टीम",
    
    soybean_title: "सोयाबीन बीज विश्लेषक",
    soybean_subtitle: "एआई-संचालित बीज क्षति का पता लगाना और कीट संक्रमण विश्लेषण",
    select_images: "अपने बीज की छवियाँ यहाँ ड्रॉप करें",
    upload_hint_single: "विश्लेषण के लिए 1 छवि अपलोड करें",
    upload_hint_batch: "बैच विश्लेषण के लिए 10 छवियों तक अपलोड करें",
    upload_analyze: "{mode} प्रारंभ करें",
    analyzing_seeds: "बीजों का विश्लेषण कर रहा है...",
    total_seeds: "कुल बीज",
    damaged: "क्षतिग्रस्त",
    quality: "गुणवत्ता",
    healthy: "स्वस्थ",
    moderate_damage: "मध्यम क्षति",
    severe_damage: "गंभीर क्षति",
    class_distribution: "वर्ग वितरण",
    recommendations: "सिफारिशें",
    individual_analysis: "व्यक्तिगत बीज विश्लेषण",
    seed_id_label: "बीज #",
    confidence_label: "विश्वास",
    severity_level: "गंभीरता स्तर",
    top_predictions: "शीर्ष 3 भविष्यवाणियाँ",
    filename: "फ़ाइल नाम",
    ai_attention_map: "एआई अटेंशन मैप",
    heatmap_caption: "हीटमैप दिखाता है कि किन क्षेत्रों ने मॉडल के निर्णय को प्रभावित किया",
    show: "दिखाएं",
    hide: "छुपाएं",
    single_analysis: "एकल विश्लेषण",
    batch_analysis: "बैच विश्लेषण",
    grad_cam_analysis: "ग्रेड-कैम विश्लेषण",
    single_desc: "शीर्ष भविष्यवाणियों सहित एक बीज का विस्तृत विश्लेषण करें",
    batch_desc: "वर्ग वितरण के साथ कई बीजों का विश्लेषण करें",
    grad_desc: "हीटमैप के साथ एआई निर्णयों का दृश्य स्पष्टीकरण",
    max_image: "अधिकतम: {count} छवि",
    max_images: "अधिकतम: {count} छवियाँ",
    
    fertilizer_title: "स्मार्ट क्रॉप एंड फर्टिलाइज़र एडवाइज़र",
    fertilizer_subtitle: "एमएल-संचालित फसल सिफारिशें • वास्तविक समय विश्लेषण • अधिकतम लाभ",
    accuracy_badge: "98% सटीकता",
    crops_badge: "20+ फसलें",
    live_analysis: "लाइव विश्लेषण",
    field_params: "खेत के पैरामीटर",
    enter_conditions: "अपनी मिट्टी और मौसम की स्थिति दर्ज करें",
    detect_location: "मेरा स्थान पता करें",
    type_location: "स्थान टाइप करें",
    fetching: "लाया जा रहा है...",
    searching: "खोज कर रहा है...",
    get_weather_data: "मौसम डेटा प्राप्त करें",
    cancel: "रद्द करें",
    city: "शहर *",
    country_optional: "देश (वैकल्पिक)",
    city_placeholder: "जैसे, दिल्ली",
    country_placeholder: "जैसे, भारत",
    soil_type: "मिट्टी का प्रकार",
    temperature: "तापमान (°C)",
    humidity: "आर्द्रता (%)",
    soil_moisture: "मिट्टी की नमी (%)",
    nitrogen: "नाइट्रोजन (N) - मिलीग्राम/किग्रा",
    phosphorous: "फॉस्फोरस (P) - मिलीग्राम/किग्रा",
    potassium: "पोटेशियम (K) - मिलीग्राम/किग्रा",
    soil_ph: "मिट्टी का पीएच",
    previous_crop: "पिछली फसल",
    season: "मौसम",
    auto: "स्वत:",
    est: "अनुमा.",
    required: "आवश्यक",
    openweathermap: "ओपनवेदरमैप",
    weather_data_from: "{location} से मौसम डेटा",
    manual_input_reminder: "कृपया नाइट्रोजन (N), फॉस्फोरस (P), और पोटेशियम (K) मान मैन्युअल रूप से दर्ज करें",
    get_recommendations: "सिफारिशें प्राप्त करें",
    analyzing: "विश्लेषण कर रहा है...",
    top_match: "सर्वश्रेष्ठ मिलान",
    soil_health: "मिट्टी का स्वास्थ्य",
    npk: "एन-पी-के",
    top_crops: "शीर्ष फसल सिफारिशें",
    click_to_optimize: "उर्वरक बजट ऑप्टिमाइज़ करने के लिए किसी भी फसल पर क्लिक करें",
    best_match: "सर्वश्रेष्ठ मिलान",
    ml_score: "एमएल स्कोर:",
    soil_label: "मिट्टी:",
    ph_label: "पीएच:",
    previous_crop_info: "पिछली फसल: {crop} | मौसम: {season}",
    click_optimize_budget: "💰 उर्वरक बजट ऑप्टिमाइज़ करने के लिए क्लिक करें →",
    farming_advice: "कृषि सलाह",
    
    budget_title: "बजट ऑप्टिमाइज़र",
    budget_info: "{crop} के लिए अपने बजट और भूमि क्षेत्र के आधार पर उर्वरक खरीद को अनुकूलित करें",
    budget_label: "💰 बजट (₹)",
    area_label: "🌾 भूमि क्षेत्र (हेक्टेयर)",
    optimize_budget: "बजट ऑप्टिमाइज़ करें",
    total_budget: "कुल बजट",
    area_ha: "क्षेत्र",
    expected_profit: "अपेक्षित लाभ",
    roi: "आरओआई",
    revenue: "राजस्व",
    spent: "खर्च",
    yield_tons: "उपज",
    recommended_fertilizer: "अनुशंसित उर्वरक संयोजन",
    new_calculation: "नई गणना",
    back: "पीछे",
    
    weather_forecast: "मौसम पूर्वानुमान",
    weather_subtitle: "आपके खेत के लिए 7-दिन का विस्तृत मौसम विश्लेषण",
    search_city: "शहर या पिन कोड खोजें...",
    daily_view: "दैनिक दृश्य",
    detailed_analysis: "विस्तृत विश्लेषण",
    feels_like: "महसूस होता है",
    humidity_short: "आर्द्रता",
    wind_speed: "हवा की गति",
    rainfall: "वर्षा",
    pressure: "दबाव",
    smart_farming_recommendations: "स्मार्ट कृषि सिफारिशें",
    seven_day_forecast: "7-दिवसीय मौसम पूर्वानुमान",
    live_location: "लाइव स्थान",
    ip_based: "आईपी आधारित",
    searched: "खोजा गया",
    updated_at: "अपडेटेड",
    sunrise: "सूर्योदय",
    sunset: "सूर्यास्त",
    uv_index: "यूवी इंडेक्स",
    moon_phase: "चंद्र कला",
    rain_chance: "बारिश की संभावना",
    snow_chance: "बर्फ की संभावना",
    farming_advice_for_day: "इस दिन के लिए कृषि सलाह:",
    weekly_weather_analysis: "साप्ताहिक मौसम विश्लेषण",
    temperature_trends: "तापमान के रुझान",
    average_high: "औसत अधिकतम",
    average_low: "औसत न्यूनतम",
    temperature_range: "तापमान सीमा",
    rainfall_summary: "वर्षा सारांश",
    total_rainfall: "कुल वर्षा",
    rainy_days: "बरसात के दिन",
    max_rainfall: "अधिकतम वर्षा",
    wind_humidity: "हवा और आर्द्रता",
    avg_wind_speed: "औसत हवा की गति",
    avg_humidity: "औसत आर्द्रता",
    uv_index_range: "यूवी इंडेक्स रेंज",
    recommended_activities: "इस सप्ताह अनुशंसित गतिविधियाँ",
    avoid_spraying: "🚫 छिड़काव से बचें",
    irrigation_needed: "💧 सिंचाई आवश्यक",
    frost_protection: "❄️ पाले से सुरक्षा",
    good_for_planting: "✅ रोपण के लिए अच्छा",
    high_temp_advice: "उच्च तापमान - पर्याप्त सिंचाई सुनिश्चित करें",
    low_temp_advice: "कम तापमान - संवेदनशील फसलों की रक्षा करें",
    heavy_rain_advice: "भारी बारिश की संभावना - उचित जल निकासी सुनिश्चित करें",
    no_rain_advice: "बारिश नहीं - तदनुसार सिंचाई की योजना बनाएं",
    strong_wind_advice: "तेज हवाएं - संरचनाओं को सुरक्षित करें और छिड़काव से बचें",
    high_humidity_advice: "उच्च आर्द्रता - फफूंद रोगों के लिए निगरानी रखें",
    fetching_weather: "आपके स्थान के लिए मौसम डेटा लाया जा रहा है...",
    weather_unavailable: "उफ! मौसम डेटा अनुपलब्ध",
    retry: "पुनः प्रयास करें",
    
    marketplace_title: "मार्केटप्लेस",
    buy_products: "उत्पाद खरीदें",
    sell_products: "उत्पाद बेचें",
    fertilizer_tools: "उर्वरक और उपकरण",
    store_page: "स्टोर पेज (निर्माणाधीन)",
    
    search_products: "उत्पाद खोजें...",
    all_categories: "सभी",
    vegetables: "सब्जियां",
    grains: "अनाज",
    fruits: "फल",
    fertilizers: "उर्वरक",
    seeds: "बीज",
    tools: "उपकरण",
    pesticides: "कीटनाशक",
    no_products: "कोई उत्पाद नहीं मिला।",
    buy_now: "अभी खरीदें",
    your_product: "आपका उत्पाद",
    seller: "विक्रेता",
    price: "मूल्य",
    quantity: "मात्रा",
    description: "विवरण",
    location: "स्थान",
    loading_products: "उत्पाद लोड हो रहे हैं...",
    purchase_request_sent: "खरीद अनुरोध भेजा गया!",
    enter_quantity: "मात्रा दर्ज करें:",
    
    sell_title: "अपना उत्पाद बेचें",
    edit_product: "उत्पाद संपादित करें",
    product_name: "उत्पाद का नाम *",
    category: "श्रेणी *",
    price_placeholder: "मूल्य (₹) *",
    quantity_placeholder: "मात्रा *",
    location_placeholder: "शहर, जिला",
    description_placeholder: "विवरण",
    product_image: "उत्पाद छवि",
    list_product: "उत्पाद सूचीबद्ध करें",
    update_product: "उत्पाद अपडेट करें",
    your_listings: "आपके सूचीबद्ध उत्पाद",
    edit: "संपादित करें",
    delete: "हटाएं",
    current_image: "वर्तमान छवि",
    uploading: "अपलोड हो रहा है...",
    product_updated: "उत्पाद अपडेट किया गया!",
    product_listed: "उत्पाद सूचीबद्ध किया गया!",
    are_you_sure: "क्या आप निश्चित हैं?",
    delete_failed: "हटाना विफल",
    
    farmer_dashboard: "किसान डैशबोर्ड",
    total_products_listed: "कुल सूचीबद्ध उत्पाद",
    orders_received: "प्राप्त ऑर्डर",
    government_schemes: "सरकारी योजनाएं",
    manage_products: "उत्पाद प्रबंधित करें →",
    view_orders: "ऑर्डर देखें →",
    view_all_schemes: "सभी योजनाएं देखें →",
    loading_dashboard: "डैशबोर्ड लोड हो रहा है...",
    
    gov_schemes_title: "महाराष्ट्र के किसानों के लिए सरकारी योजनाएं",
    eligibility_label: "पात्रता:",
    benefits_label: "लाभ:",
    apply_now: "अभी आवेदन करें →",
    loading_schemes: "योजनाएं लोड हो रही हैं...",
    
    my_orders_title: "मेरे ऑर्डर",
    buying: "खरीदारी",
    selling: "बिक्री",
    placed: "रखा गया",
    accept: "स्वीकार करें",
    reject: "अस्वीकार करें",
    pending: "लंबित",
    accepted: "स्वीकृत",
    rejected: "अस्वीकृत",
    loading_orders: "ऑर्डर लोड हो रहे हैं...",
    no_orders: "कोई ऑर्डर नहीं मिला।",
    accept_btn: "स्वीकार करें",
    reject_btn: "अस्वीकार करें",
    status_update_failed: "स्थिति अद्यतन विफल",
    
    order_history: "ऑर्डर इतिहास",
    no_orders_yet: "अभी तक कोई ऑर्डर नहीं।",
    order_total: "कुल",
    each: "प्रत्येक",
    
    ai_assistant: "एग्रीस्मार्ट एआई सहायक",
    powered_by: "गूगल जेमिनी 2.5 फ्लैश द्वारा संचालित",
    ask_me: "कृषि के बारे में कुछ भी पूछें...",
    welcome_message: "नमस्ते! 👋 मैं आपका कृषि एआई सहायक हूं। मुझसे फसल प्रबंधन, कीट नियंत्रण, सिंचाई, बाजार मूल्य, सरकारी योजनाओं और बहुत कुछ के बारे में पूछें!",
    try_asking: "मुझसे पूछने का प्रयास करें:",
    crop_management: "🌾 फसल प्रबंधन",
    pest_control: "🐛 कीट नियंत्रण",
    irrigation: "💧 सिंचाई तकनीकें",
    market_prices: "📈 बाजार मूल्य",
    gov_schemes_chat: "🏛️ सरकारी योजनाएं",
    type_message: "अपना संदेश टाइप करें...",
    clear_chat: "चैट साफ करें",
    send: "भेजें",
    error_message_chat: "क्षमा करें, एक त्रुटि हुई। कृपया बाद में पुनः प्रयास करें।",
    network_error: "नेटवर्क त्रुटि। कृपया अपना इंटरनेट कनेक्शन जांचें।",
    too_many_requests: "बहुत सारे अनुरोध। कृपया एक क्षण प्रतीक्षा करें और पुनः प्रयास करें।",
    server_error: "सर्वर त्रुटि। कृपया कुछ क्षणों में पुनः प्रयास करें।",
    rate_limit_warning: "⚠️ आप दर सीमा तक पहुँच गए हैं। कृपया अधिक संदेश भेजने से पहले एक क्षण प्रतीक्षा करें।",
  },
  
  mr: {

    schemes_data_mr: [
  {
    id: 1,
    scheme_name: "प्रधानमंत्री किसान सन्मान निधी (पीएम-किसान)",
    description: "लहान आणि सीमांत शेतकऱ्यांना दरवर्षी ₹6000 प्रदान करणारी उत्पन्न सहाय्य योजना.",
    eligibility: "लागवडीयोग्य जमीन असलेले सर्व लहान आणि सीमांत शेतकरी.",
    benefits: "दरवर्षी ₹6000 तीन समान हप्त्यांमध्ये थेट बँक खात्यात.",
    application_link: "https://pmkisan.gov.in/"
  },
  {
    id: 2,
    scheme_name: "प्रधानमंत्री पीक विमा योजना (पीएमएफबीवाय)",
    description: "नैसर्गिक आपत्तींमुळे पीक नुकसानापासून शेतकऱ्यांचे संरक्षण करण्यासाठी पीक विमा योजना.",
    eligibility: "अधिसूचित क्षेत्रांमध्ये अधिसूचित पिके घेणारे शेतकरी.",
    benefits: "पीक अपयशाच्या स्थितीत विमा संरक्षण आणि आर्थिक सहाय्य.",
    application_link: "https://pmfby.gov.in/"
  },
  {
    id: 3,
    scheme_name: "महात्मा ज्योतिराव फुले शेतकरी कर्ज मुक्ती योजना",
    description: "महाराष्ट्र सरकारने शेतकऱ्यांसाठी सुरू केलेली कर्जमाफी योजना.",
    eligibility: "महाराष्ट्रातील बँकांमधून पीक कर्ज घेतलेले शेतकरी.",
    benefits: "₹2 लाख पर्यंत कर्जमाफी.",
    application_link: "https://mjpsky.maharashtra.gov.in/"
  },
  {
    id: 4,
    scheme_name: "मृदा आरोग्य कार्ड योजना",
    description: "शेतकऱ्यांना खतांच्या शिफारशींसह मृदा आरोग्य कार्डे प्रदान करते.",
    eligibility: "भारतातील सर्व शेतकरी.",
    benefits: "चांगली पीक उत्पादकता आणि कमी खत खर्च.",
    application_link: "https://soilhealth.dac.gov.in/"
  },
  {
    id: 5,
    scheme_name: "किसान क्रेडिट कार्ड (केसीसी)",
    description: "शेतकऱ्यांना शेती आणि संलग्न क्रियाकलापांसाठी सुलभ कर्ज प्रदान करते.",
    eligibility: "शेती किंवा संलग्न क्रियाकलापांमध्ये गुंतलेले शेतकरी.",
    benefits: "कमी व्याजदरांसह अल्पकालीन कर्ज.",
    application_link: "https://www.myscheme.gov.in/schemes/kcc"
  }
],
    // Marathi translations – fallback to English for missing keys
    app_name: "अग्रीस्मार्ट एआय",
    home: "मुख्यपृष्ठ",
    features: "वैशिष्ट्ये",
    about: "आमच्याबद्दल",
    contact: "संपर्क करा",
    sign_in: "साइन इन करा",
    sign_up: "साइन अप करा",
    dashboard: "डॅशबोर्ड",
    marketplace: "मार्केटप्लेस",
    schemes: "सरकारी योजना",
    my_orders: "माझे ऑर्डर",
    logout: "लॉग आउट",
    loading: "लोड करत आहे...",
    error: "त्रुटी",
    retry: "पुन्हा प्रयत्न करा",
    back_home: "← मुख्यपृष्ठावर परत",
    days: "दिवस",
    
    hero_title: "स्मार्ट शेती",
    hero_title_gradient: "एआय-संचालित उपाय",
    hero_subtitle: "अत्याधुनिक कृत्रिम बुद्धिमत्तेसह शेतीत क्रांती घडवून आणणे. आपल्या कृषी उत्पन्नाचे विश्लेषण करा, ऑप्टिमाइझ करा आणि जास्तीत जास्त वाढवा.",
    explore_features: "वैशिष्ट्ये एक्सप्लोर करा",
    get_started_free: "विनामूल्य प्रारंभ करा",
    our_tools: "आमची एआय-संचालित साधने",
    soybean_analyzer: "सोयाबीन विश्लेषक",
    soybean_desc: "एआय-संचालित बीज नुकसान शोध आणि कीट विश्लेषण",
    fertilizer_optimizer: "खत ऑप्टिमाइझर",
    fertilizer_desc: "स्मार्ट खत शिफारसी",
    budget_optimizer: "बजेट ऑप्टिमाइझर",
    budget_desc: "इष्टतम वाटपासह उत्पादन वाढवा",
    weather_insights: "हवामान अंतर्दृष्टी",
    weather_desc: "वास्तविक-वेळ हवामान आणि शेती शिफारसी",
    learn_more: "अधिक जाणून घ्या →",
    stat_detection_accuracy: "शोध अचूकता",
    stat_yield_increase: "उत्पादन वाढ",
    stat_happy_farmers: "समाधानी शेतकरी",
    stat_ai_assistance: "एआय सहाय्य",
    footer_copyright: "© 2024 अग्रीस्मार्ट एआय. सर्व हक्क राखीव.",
    
    soybean: "सोयाबीन",
    fertilizer: "खत",
    budget: "बजेट",
    weather: "हवामान",
    our_mission: "आमचे ध्येय",
    our_team: "आमची टीम",
    
    soybean_title: "सोयाबीन बियाणे विश्लेषक",
    soybean_subtitle: "एआय-संचालित बीज नुकसान शोध आणि कीट संसर्ग विश्लेषण",
    select_images: "आपल्या बियाणांच्या प्रतिमा येथे टाका",
    upload_hint_single: "विश्लेषणासाठी 1 प्रतिमा अपलोड करा",
    upload_hint_batch: "बॅच विश्लेषणासाठी 10 प्रतिमांपर्यंत अपलोड करा",
    upload_analyze: "{mode} प्रारंभ करा",
    analyzing_seeds: "बियाण्यांचे विश्लेषण करत आहे...",
    total_seeds: "एकूण बियाणे",
    damaged: "क्षतिग्रस्त",
    quality: "गुणवत्ता",
    healthy: "निरोगी",
    moderate_damage: "मध्यम नुकसान",
    severe_damage: "गंभीर नुकसान",
    class_distribution: "वर्ग वितरण",
    recommendations: "शिफारसी",
    individual_analysis: "वैयक्तिक बियाणे विश्लेषण",
    seed_id_label: "बियाणे #",
    confidence_label: "विश्वास",
    severity_level: "तीव्रता पातळी",
    top_predictions: "टॉप 3 अंदाज",
    filename: "फाइलनाव",
    ai_attention_map: "एआय अटेंशन नकाशा",
    heatmap_caption: "हीटमॅप दर्शवितो की कोणत्या क्षेत्रांनी मॉडेलच्या निर्णयावर प्रभाव टाकला",
    show: "दाखवा",
    hide: "लपवा",
    single_analysis: "एकल विश्लेषण",
    batch_analysis: "बॅच विश्लेषण",
    grad_cam_analysis: "ग्रेड-कॅम विश्लेषण",
    single_desc: "शीर्ष अंदाजांसह एका बियाण्याचे तपशीलवार विश्लेषण करा",
    batch_desc: "वर्ग वितरणासह अनेक बियाण्यांचे विश्लेषण करा",
    grad_desc: "हीटमॅपसह एआय निर्णयांचे दृश्य स्पष्टीकरण",
    max_image: "कमाल: {count} प्रतिमा",
    max_images: "कमाल: {count} प्रतिमा",
    
    fertilizer_title: "स्मार्ट पीक आणि खत सल्लागार",
    fertilizer_subtitle: "एमएल-संचालित पीक शिफारसी • वास्तविक-वेळ विश्लेषण • जास्तीत जास्त नफा",
    accuracy_badge: "98% अचूकता",
    crops_badge: "20+ पिके",
    live_analysis: "लाइव्ह विश्लेषण",
    field_params: "शेताचे पॅरामीटर्स",
    enter_conditions: "आपली माती आणि हवामान परिस्थिती प्रविष्ट करा",
    detect_location: "माझे स्थान शोधा",
    type_location: "स्थान टाइप करा",
    fetching: "आणत आहे...",
    searching: "शोधत आहे...",
    get_weather_data: "हवामान डेटा मिळवा",
    cancel: "रद्द करा",
    city: "शहर *",
    country_optional: "देश (ऐच्छिक)",
    city_placeholder: "उदा., मुंबई",
    country_placeholder: "उदा., भारत",
    soil_type: "मातीचा प्रकार",
    temperature: "तापमान (°C)",
    humidity: "आर्द्रता (%)",
    soil_moisture: "मातीची ओलावा (%)",
    nitrogen: "नायट्रोजन (N) - मिलीग्राम/किग्रा",
    phosphorous: "फॉस्फरस (P) - मिलीग्राम/किग्रा",
    potassium: "पोटॅशियम (K) - मिलीग्राम/किग्रा",
    soil_ph: "मातीची पीएच",
    previous_crop: "मागील पीक",
    season: "हंगाम",
    auto: "स्वयं",
    est: "अंदा.",
    required: "आवश्यक",
    openweathermap: "ओपनवेदरमॅप",
    weather_data_from: "{location} कडून हवामान डेटा",
    manual_input_reminder: "कृपया नायट्रोजन (N), फॉस्फरस (P), आणि पोटॅशियम (K) मूल्ये व्यक्तिचलितपणे प्रविष्ट करा",
    get_recommendations: "शिफारसी मिळवा",
    analyzing: "विश्लेषण करत आहे...",
    top_match: "सर्वोत्तम जुळणी",
    soil_health: "मातीचे आरोग्य",
    npk: "एन-पी-के",
    top_crops: "शीर्ष पीक शिफारसी",
    click_to_optimize: "खत बजेट ऑप्टिमाइझ करण्यासाठी कोणत्याही पीक वर क्लिक करा",
    best_match: "सर्वोत्तम जुळणी",
    ml_score: "एमएल स्कोअर:",
    soil_label: "माती:",
    ph_label: "पीएच:",
    previous_crop_info: "मागील पीक: {crop} | हंगाम: {season}",
    click_optimize_budget: "💰 खत बजेट ऑप्टिमाइझ करण्यासाठी क्लिक करा →",
    farming_advice: "शेती सल्ला",
    
    budget_title: "बजेट ऑप्टिमाइझर",
    budget_info: "{crop} साठी आपल्या बजेट आणि जमीन क्षेत्रावर आधारित खत खरेदी ऑप्टिमाइझ करा",
    budget_label: "💰 बजेट (₹)",
    area_label: "🌾 जमीन क्षेत्र (हेक्टर)",
    optimize_budget: "बजेट ऑप्टिमाइझ करा",
    total_budget: "एकूण बजेट",
    area_ha: "क्षेत्र",
    expected_profit: "अपेक्षित नफा",
    roi: "आरओआय",
    revenue: "महसूल",
    spent: "खर्च",
    yield_tons: "उत्पादन",
    recommended_fertilizer: "शिफारस केलेले खत संयोजन",
    new_calculation: "नवीन गणना",
    back: "मागे",
    
    weather_forecast: "हवामान अंदाज",
    weather_subtitle: "आपल्या शेतासाठी 7-दिवसांचे तपशीलवार हवामान विश्लेषण",
    search_city: "शहर किंवा पिन कोड शोधा...",
    daily_view: "दैनिक दृश्य",
    detailed_analysis: "तपशीलवार विश्लेषण",
    feels_like: "वाटते",
    humidity_short: "आर्द्रता",
    wind_speed: "वाऱ्याचा वेग",
    rainfall: "पाऊस",
    pressure: "दबाव",
    smart_farming_recommendations: "स्मार्ट शेती शिफारसी",
    seven_day_forecast: "7-दिवसीय हवामान अंदाज",
    live_location: "लाइव्ह स्थान",
    ip_based: "आयपी आधारित",
    searched: "शोधले",
    updated_at: "अद्यतनित",
    sunrise: "सूर्योदय",
    sunset: "सूर्यास्त",
    uv_index: "यूव्ही इंडेक्स",
    moon_phase: "चंद्र कला",
    rain_chance: "पावसाची शक्यता",
    snow_chance: "बर्फाची शक्यता",
    farming_advice_for_day: "या दिवसासाठी शेती सल्ला:",
    weekly_weather_analysis: "साप्ताहिक हवामान विश्लेषण",
    temperature_trends: "तापमान ट्रेंड",
    average_high: "सरासरी कमाल",
    average_low: "सरासरी किमान",
    temperature_range: "तापमान श्रेणी",
    rainfall_summary: "पाऊस सारांश",
    total_rainfall: "एकूण पाऊस",
    rainy_days: "पाऊस दिवस",
    max_rainfall: "कमाल पाऊस",
    wind_humidity: "वारा आणि आर्द्रता",
    avg_wind_speed: "सरासरी वाऱ्याचा वेग",
    avg_humidity: "सरासरी आर्द्रता",
    uv_index_range: "यूव्ही इंडेक्स श्रेणी",
    recommended_activities: "या आठवड्यासाठी शिफारस केलेल्या क्रिया",
    avoid_spraying: "🚫 फवारणी टाळा",
    irrigation_needed: "💧 सिंचन आवश्यक",
    frost_protection: "❄️ दंव संरक्षण",
    good_for_planting: "✅ लागवडीसाठी चांगले",
    high_temp_advice: "उच्च तापमान - पुरेशी सिंचन सुनिश्चित करा",
    low_temp_advice: "कमी तापमान - संवेदनशील पिकांचे संरक्षण करा",
    heavy_rain_advice: "मुसळधार पावसाची शक्यता - योग्य निचरा सुनिश्चित करा",
    no_rain_advice: "पाऊस नाही - त्यानुसार सिंचनाची योजना करा",
    strong_wind_advice: "जोरदार वारे - रचना सुरक्षित करा आणि फवारणी टाळा",
    high_humidity_advice: "उच्च आर्द्रता - बुरशीजन्य रोगांसाठी लक्ष ठेवा",
    fetching_weather: "आपल्या स्थानासाठी हवामान डेटा आणत आहे...",
    weather_unavailable: "अरेरे! हवामान डेटा उपलब्ध नाही",
    retry: "पुन्हा प्रयत्न करा",
    
    marketplace_title: "मार्केटप्लेस",
    buy_products: "उत्पादने खरेदी करा",
    sell_products: "उत्पादने विका",
    fertilizer_tools: "खत आणि साधने",
    store_page: "स्टोअर पेज (बांधकामाधीन)",
    
    search_products: "उत्पादने शोधा...",
    all_categories: "सर्व",
    vegetables: "भाज्या",
    grains: "धान्ये",
    fruits: "फळे",
    fertilizers: "खते",
    seeds: "बियाणे",
    tools: "साधने",
    pesticides: "कीटकनाशके",
    no_products: "कोणतीही उत्पादने आढळली नाहीत.",
    buy_now: "आता खरेदी करा",
    your_product: "आपले उत्पादन",
    seller: "विक्रेता",
    price: "किंमत",
    quantity: "प्रमाण",
    description: "वर्णन",
    location: "स्थान",
    loading_products: "उत्पादने लोड होत आहेत...",
    purchase_request_sent: "खरेदी विनंती पाठविली!",
    enter_quantity: "प्रमाण प्रविष्ट करा:",
    
    sell_title: "आपले उत्पादन विका",
    edit_product: "उत्पादन संपादित करा",
    product_name: "उत्पादनाचे नाव *",
    category: "श्रेणी *",
    price_placeholder: "किंमत (₹) *",
    quantity_placeholder: "प्रमाण *",
    location_placeholder: "शहर, जिल्हा",
    description_placeholder: "वर्णन",
    product_image: "उत्पादन प्रतिमा",
    list_product: "उत्पादन सूचीबद्ध करा",
    update_product: "उत्पादन अद्यतनित करा",
    your_listings: "आपली सूचीबद्ध उत्पादने",
    edit: "संपादित करा",
    delete: "हटवा",
    current_image: "सध्याची प्रतिमा",
    uploading: "अपलोड करत आहे...",
    product_updated: "उत्पादन अद्यतनित केले!",
    product_listed: "उत्पादन सूचीबद्ध केले!",
    are_you_sure: "आपण निश्चित आहात?",
    delete_failed: "हटविण्यात अयशस्वी",
    
    farmer_dashboard: "शेतकरी डॅशबोर्ड",
    total_products_listed: "एकूण सूचीबद्ध उत्पादने",
    orders_received: "प्राप्त ऑर्डर",
    government_schemes: "सरकारी योजना",
    manage_products: "उत्पादने व्यवस्थापित करा →",
    view_orders: "ऑर्डर पहा →",
    view_all_schemes: "सर्व योजना पहा →",
    loading_dashboard: "डॅशबोर्ड लोड होत आहे...",
    
    gov_schemes_title: "महाराष्ट्र शेतकऱ्यांसाठी सरकारी योजना",
    eligibility_label: "पात्रता:",
    benefits_label: "लाभ:",
    apply_now: "आता अर्ज करा →",
    loading_schemes: "योजना लोड होत आहेत...",
    
    my_orders_title: "माझे ऑर्डर",
    buying: "खरेदी",
    selling: "विक्री",
    placed: "ठेवला",
    accept: "स्वीकारा",
    reject: "नाकारा",
    pending: "प्रलंबित",
    accepted: "स्वीकारले",
    rejected: "नाकारले",
    loading_orders: "ऑर्डर लोड होत आहेत...",
    no_orders: "कोणतेही ऑर्डर सापडले नाहीत.",
    accept_btn: "स्वीकारा",
    reject_btn: "नाकारा",
    status_update_failed: "स्थिती अद्यतन अयशस्वी",
    
    order_history: "ऑर्डर इतिहास",
    no_orders_yet: "अद्याप कोणतेही ऑर्डर नाहीत.",
    order_total: "एकूण",
    each: "प्रत्येकी",
    
    ai_assistant: "अग्रीस्मार्ट एआय सहाय्यक",
    powered_by: "गूगल जेमिनी 2.5 फ्लॅश द्वारे संचालित",
    ask_me: "शेतीबद्दल काहीही विचारा...",
    welcome_message: "नमस्कार! 👋 मी आपला कृषी एआय सहाय्यक आहे. मला पीक व्यवस्थापन, कीटक नियंत्रण, सिंचन, बाजारभाव, सरकारी योजना आणि बरेच काही विचारा!",
    try_asking: "मला विचारून पहा:",
    crop_management: "🌾 पीक व्यवस्थापन",
    pest_control: "🐛 कीटक नियंत्रण",
    irrigation: "💧 सिंचन तंत्रे",
    market_prices: "📈 बाजारभाव",
    gov_schemes_chat: "🏛️ सरकारी योजना",
    type_message: "आपला संदेश टाइप करा...",
    clear_chat: "चॅट साफ करा",
    send: "पाठवा",
    error_message_chat: "क्षमस्व, एक त्रुटी आली. कृपया नंतर पुन्हा प्रयत्न करा.",
    network_error: "नेटवर्क त्रुटी. कृपया आपले इंटरनेट कनेक्शन तपासा.",
    too_many_requests: "खूप विनंत्या. कृपया एक क्षण थांबा आणि पुन्हा प्रयत्न करा.",
    server_error: "सर्व्हर त्रुटी. कृपया काही क्षणात पुन्हा प्रयत्न करा.",
    rate_limit_warning: "⚠️ आपण दर मर्यादा गाठली आहे. कृपया अधिक संदेश पाठविण्यापूर्वी एक क्षण थांबा.",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key, params = {}) => {
    let text = translations[language]?.[key] || translations.en[key] || key;
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};